package:
  name: suitcase
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/NSLS-II/suitcase.git
  git_rev: master

build:
  number: 0

  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six
    - dataportal
    - h5py
    - numpy

test:
  requires:
    - nslsii_dev_configuration

  imports:
    - suitcase
