package:
  name: protobuf
  version: {{ '{}.{}.post{}+'.format(*(environ.get('GIT_DESCRIBE_TAG', 'v3-a-1-5-g'))[1:].split('-')) }}{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: git@github.com:google/protobuf.git
  md5: master

build:
    number: 0
    string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - setuptools
    - six

about:
  home: http://code.google.com/p/protobuf/
  license: New BSD License
  summary: 'Protocol Buffers'
