package:
  name: databroker
  version: v0.3.0

source:
  git_url: https://github.com/NSLS-II/databroker
  git_rev: v0.3.0

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - pandas
    - pims
    - metadatastore >=v0.2.0
    - filestore >=v0.2.0
    - channelarchiver
    - six
    - tzlocal

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - databroker
    - databroker.testing
    - databroker.examples
    - databroker.examples.sample_data
    - databroker.utils

about:
  home: https://github.com/NSLS-II/databroker
  license: BSD
