package:
    name: pims
    version: {{ environ.get('GIT_DESCRIBE_TAG', 'v0')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
    git_url: https://github.com/soft-matter/pims.git
    git_rev: master

build:
    number: 0
    string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}

requirements:
    build:
        - python
        - six
        - setuptools
        - slicerator
        - numpy

    run:
        - python
        - six
        - numpy
        - scipy
        - pillow
        - tifffile
        - slicerator

test:
    imports:
        - pims

about:
    home: http://soft-matter.github.io/pims/
    license: BSD
