
package:
    name: pyepics
    version: {{ environ.get('GIT_DESCRIBE_TAG','')}}.post{{ environ.get('GIT_DESCRIBE_NUMBER','') }}


source:
    git_url: https://github.com/pyepics/pyepics.git
    git_rev: master

build:
    number: 0
    string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}

requirements:
    build:
        - python
        - setuptools
        - numpy
        - epics-base
    run:
        - python
        - numpy
        - epics-base

test:
    imports:
        - epics

about:
    home: http://pyepics.github.io/pyepics/
    license: Epics Open License
    summary: Python interface to Epics Channel Access
