package:
  name: ixs_analysis
  version: '0.1'


build:
  number: 0


requirements:
  run:
    - ixs_configuration
    - matplotlib
    - dataportal
    - openpyxl
    - ipython-notebook
    - vistrails
    - scikit-xray
