package:
  name: boltons
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/mahmoud/boltons.git
  git_rev: master

build:
  number: 0

  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}


requirements:
  build:
    - python
    - pytest

  run:
    - python

test:
  imports:
    - boltons
    - boltons.cacheutils
    - boltons.dictutils
    - boltons.fileutils
    - boltons.gcutils
    - boltons.listutils
    - boltons.namedutils
    - boltons.socketutils
    - boltons.tableutils
    - boltons.typeutils
    - boltons.debugutils
    - boltons.easterutils
    - boltons.formatutils
    - boltons.iterutils
    - boltons.mathutils
    - boltons.queueutils
    - boltons.statsutils
    - boltons.tbutils
    - boltons.tzutils
    - boltons.deprutils
    - boltons.excutils
    - boltons.funcutils
    - boltons.jsonutils
    - boltons.mboxutils
    - boltons.setutils
    - boltons.strutils
    - boltons.timeutils

