package:
  name: hkl
  version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('-', '.')}}.post{{ environ.get('GIT_DESCRIBE_NUMBER','') }}

source:
    git_url: https://github.com/picca/hkl
    git_rev: next
    
build:
  number: 0

requirements:
  build:
    - python
    - gobject-introspection
    - gsl
    - libtool
    - automake
    - autoconf
    - pkg-config
  run:
    - python
    - pygobject
    - numpy

about:
  home: http://repo.or.cz/w/hkl.git/
  license: LGPL
