package:
  name: datamuxer
  version: v0.3.0

source:
  git_url: https://github.com/NSLS-II/datamuxer
  git_rev: v0.3.0

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - pandas
    - six
    - scipy
    - tzlocal

test:
  requires:
    - nslsii_dev_configuration
    - databroker
  imports:
    - datamuxer

about:
  home: https://github.com/NSLS-II/datamuxer
  license: BSD
