package:
  name: suitcase
  version: v0.2.1

source:
  git_url: https://github.com/NSLS-II/suitcase.git
  git_rev: v0.2.1

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six
    - dataportal
    - h5py
    - numpy

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - suitcase
