package:
  name: mongoengine
  version: !!str 0.8.7

source:
  fn: mongoengine-0.8.7.tar.gz
  url: https://github.com/MongoEngine/mongoengine/archive/v0.8.7.tar.gz
  md5: 96e78c892d3e30ed0c813e8fa5fe133e
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mongoengine = mongoengine:main
    #
    # Would create an entry point called mongoengine that calls mongoengine.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - pymongo ==2.8

  run:
    - python
    - pymongo ==2.8

test:
  # Python imports
  imports:
    - bson
    - mongoengine
    - mongoengine.base
    - mongoengine.django
    - mongoengine.django.mongo_auth
    - mongoengine.queryset

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://mongoengine.org/
  license: MIT License
  summary: 'MongoEngine is a Python Object-Document Mapper for working with MongoDB.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
