package:
  name: vistrails
  version: {{ environ['GIT_DESCRIBE_TAG'][1:] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/VisTrails/VisTrails.git
  git_branch: master


build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}

  patches:
    - qt_sip.patch

build:
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - vistrails = vistrails:main
    #
    # Would create an entry point called vistrails that calls vistrails.main()

    - vistrails = vistrails.run:main

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - certifi
    - ssl_match_hostname

  run:
    - python
    - numpy
    - scipy
    - pyqt
    - matplotlib
    - vtk
    - ipython-qtconsole
    - xlrd
    - xlwt
    - certifi
    - ssl_match_hostname

test:
  # Python imports
  imports:
    - vistrails
    - vistrails.api
    - vistrails.core
    - vistrails.core.analogy
    - vistrails.core.bundles
    - vistrails.core.cache
    - vistrails.core.collection
    - vistrails.core.data_structures
    - vistrails.core.db
    - vistrails.core.interpreter
    - vistrails.core.layout
    - vistrails.core.log
    - vistrails.core.mashup
    - vistrails.core.modules
    - vistrails.core.paramexplore
    - vistrails.core.publishing
    - vistrails.core.query
    - vistrails.core.repository
    - vistrails.core.repository.poster
    - vistrails.core.system
    - vistrails.core.utils
    - vistrails.core.vistrail
    - vistrails.db
    - vistrails.db.bin
    - vistrails.db.domain
    - vistrails.db.persistence
    - vistrails.db.services
    - vistrails.db.tests
    - vistrails.db.versions
    - vistrails.db.versions.v0_3_0
    - vistrails.db.versions.v0_3_0.domain
    - vistrails.db.versions.v0_3_0.persistence
    - vistrails.db.versions.v0_3_0.persistence.xml
    - vistrails.db.versions.v0_3_1
    - vistrails.db.versions.v0_3_1.domain
    - vistrails.db.versions.v0_3_1.persistence
    - vistrails.db.versions.v0_3_1.translate
    - vistrails.db.versions.v0_5_0
    - vistrails.db.versions.v0_5_0.domain
    - vistrails.db.versions.v0_5_0.persistence
    - vistrails.db.versions.v0_5_0.persistence.sql
    - vistrails.db.versions.v0_5_0.persistence.xml
    - vistrails.db.versions.v0_5_0.translate
    - vistrails.db.versions.v0_6_0
    - vistrails.db.versions.v0_6_0.domain
    - vistrails.db.versions.v0_6_0.persistence
    - vistrails.db.versions.v0_6_0.persistence.sql
    - vistrails.db.versions.v0_6_0.persistence.xml
    - vistrails.db.versions.v0_6_0.translate
    - vistrails.db.versions.v0_7_0
    - vistrails.db.versions.v0_7_0.domain
    - vistrails.db.versions.v0_7_0.persistence
    - vistrails.db.versions.v0_7_0.persistence.sql
    - vistrails.db.versions.v0_7_0.persistence.xml
    - vistrails.db.versions.v0_7_0.translate
    - vistrails.db.versions.v0_8_0
    - vistrails.db.versions.v0_8_0.domain
    - vistrails.db.versions.v0_8_0.persistence
    - vistrails.db.versions.v0_8_0.persistence.sql
    - vistrails.db.versions.v0_8_0.persistence.xml
    - vistrails.db.versions.v0_8_0.translate
    - vistrails.db.versions.v0_8_1
    - vistrails.db.versions.v0_8_1.domain
    - vistrails.db.versions.v0_8_1.persistence
    - vistrails.db.versions.v0_8_1.translate
    - vistrails.db.versions.v0_9_0
    - vistrails.db.versions.v0_9_0.domain
    - vistrails.db.versions.v0_9_0.persistence
    - vistrails.db.versions.v0_9_0.persistence.sql
    - vistrails.db.versions.v0_9_0.persistence.xml
    - vistrails.db.versions.v0_9_0.translate
    - vistrails.db.versions.v0_9_1
    - vistrails.db.versions.v0_9_1.domain
    - vistrails.db.versions.v0_9_1.persistence
    - vistrails.db.versions.v0_9_1.persistence.sql
    - vistrails.db.versions.v0_9_1.persistence.xml
    - vistrails.db.versions.v0_9_1.translate
    - vistrails.db.versions.v0_9_2
    - vistrails.db.versions.v0_9_2.domain
    - vistrails.db.versions.v0_9_2.persistence
    - vistrails.db.versions.v0_9_2.translate
    - vistrails.db.versions.v0_9_3
    - vistrails.db.versions.v0_9_3.domain
    - vistrails.db.versions.v0_9_3.persistence
    - vistrails.db.versions.v0_9_3.persistence.sql
    - vistrails.db.versions.v0_9_3.persistence.xml
    - vistrails.db.versions.v0_9_3.translate
    - vistrails.db.versions.v0_9_4
    - vistrails.db.versions.v0_9_4.domain
    - vistrails.db.versions.v0_9_4.persistence
    - vistrails.db.versions.v0_9_4.persistence.sql
    - vistrails.db.versions.v0_9_4.persistence.xml
    - vistrails.db.versions.v0_9_4.translate
    - vistrails.db.versions.v0_9_5
    - vistrails.db.versions.v0_9_5.domain
    - vistrails.db.versions.v0_9_5.persistence
    - vistrails.db.versions.v0_9_5.persistence.sql
    - vistrails.db.versions.v0_9_5.persistence.xml
    - vistrails.db.versions.v0_9_5.translate
    - vistrails.db.versions.v1_0_0
    - vistrails.db.versions.v1_0_0.domain
    - vistrails.db.versions.v1_0_0.persistence
    - vistrails.db.versions.v1_0_0.persistence.sql
    - vistrails.db.versions.v1_0_0.persistence.xml
    - vistrails.db.versions.v1_0_0.translate
    - vistrails.db.versions.v1_0_1
    - vistrails.db.versions.v1_0_1.domain
    - vistrails.db.versions.v1_0_1.persistence
    - vistrails.db.versions.v1_0_1.persistence.sql
    - vistrails.db.versions.v1_0_1.persistence.xml
    - vistrails.db.versions.v1_0_1.translate
    - vistrails.db.versions.v1_0_2
    - vistrails.db.versions.v1_0_2.domain
    - vistrails.db.versions.v1_0_2.persistence
    - vistrails.db.versions.v1_0_2.persistence.sql
    - vistrails.db.versions.v1_0_2.persistence.xml
    - vistrails.db.versions.v1_0_2.translate
    - vistrails.db.versions.v1_0_3
    - vistrails.db.versions.v1_0_3.domain
    - vistrails.db.versions.v1_0_3.persistence
    - vistrails.db.versions.v1_0_3.persistence.sql
    - vistrails.db.versions.v1_0_3.persistence.xml
    - vistrails.db.versions.v1_0_3.translate
    - vistrails.gui
    - vistrails.gui.bundles
    - vistrails.gui.collection
    - vistrails.gui.extras
    - vistrails.gui.extras.core
    - vistrails.gui.extras.core.db
    - vistrails.gui.mashups
    - vistrails.gui.modules
    - vistrails.gui.modules.resources
    - vistrails.gui.paramexplore
    - vistrails.gui.resources
    - vistrails.packages
    - vistrails.packages.CLTools
    - vistrails.packages.ImageMagick
#    - vistrails.packages.JobSubmission
    - vistrails.packages.SUDSWebServices
    - vistrails.packages.analytics
    - vistrails.packages.controlflow
    - vistrails.packages.dialogs
    - vistrails.packages.matplotlib
    - vistrails.packages.parallelflow
    - vistrails.packages.persistence
    - vistrails.packages.pipelineEdit
    - vistrails.packages.pythonCalc
    - vistrails.packages.pythonCalcQt
    - vistrails.packages.qgis
    - vistrails.packages.rpy
    - vistrails.packages.spreadsheet
    - vistrails.packages.spreadsheet.widgets
    - vistrails.packages.spreadsheet.widgets.iebrowser [win]
#    - vistrails.packages.spreadsheet.widgets.imageviewer
#    - vistrails.packages.spreadsheet.widgets.richtext
#    - vistrails.packages.spreadsheet.widgets.svg
#    - vistrails.packages.spreadsheet.widgets.webview
    - vistrails.packages.sql
    - vistrails.packages.tabledata
    - vistrails.packages.tabledata.convert
#   - vistrails.packages.tabledata.read
    - vistrails.packages.vtk
    - vistrails.packages.vtlcreator
    - vistrails.packages.webServices
    - vistrails.tests
    - vistrails.tests.resources
    - vistrails.tests.resources.import_pkg
#    - vistrails.tests.resources.import_pkg.test_import_pkg
    - vistrails.tests.resources.import_targets

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - vistrails --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.vistrails.org/
  license: BSD License
  summary: 'Data analysis and visualization tool'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
