package:
  name: databroker
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/NSLS-II/databroker
  git_rev: master

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - pandas
    - pims
    - metadatastore >=0.2.0
    - filestore >=0.2.0
    - channelarchiver
    - six
    - tzlocal

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - databroker
    - databroker.testing
    - databroker.examples
    - databroker.examples.sample_data
    - databroker.utils

about:
  home: https://github.com/NSLS-II/databroker
  license: BSD
