package: bubblegum
user: edill
#===============================================================================
# Build Matrix Options
# Thes options may be a single item, a list or empty
# The resulting number of builds is [platform * engine * env]
#===============================================================================
platform:
 - linux-64
 - osx-64
## The engine are the inital conda packages you want to run with
engine:
 - python=2.7
 - python=3.4

install:
 - conda config --add channels Nikea
# before_script:
#   - echo "before_script!"
script:
  - conda build .
# after_script:
#   - echo "The build was a $BINSTAR_BUILD_RESULT" | tee artifact1.txt
## This will be run only after a successfull build
# after_success:
#   - echo "after_success!"
## This will be run only after a build failure
# after_failure:
#   - echo "after_failure!"

## Build Artifacts: upload anything you want!
## Your build artifacts will be put into the website
## http://artifacts.build.binstar.info/USERNAME/PACKGE_NAME/BUILD_NO
## You can store all logs or any derived data here
## Remember, the site http://artifacts.build.binstar.info is NOT secure and does not
## require a user to log in to view
#build_artifacts:
#  - "*.log"

## Build Targets: Upload these files to your binstar package
## build targets may be a list of files (globs allows) to upload
## The special build targets 'conda' and 'pypi' may be used to
## upload conda builds
## e.g. conda is an alias for /opt/anaconda/conda-bld/<os-arch>/*.tar.bz2
build_targets: conda

iotimeout : 600
