package:
  name: clint
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER','') }}

source:
  git_url: https://github.com/kennethreitz/clint
  git_rev: v0.4.1

requirements:
  build:
    - python
    - pip
    - args

  run:
    - python
    - args

test:
  imports:
    - clint

about:
  home: https://github.com/kennethreitz/clint
  license: ISC
  summary: Python Command-line Application Tools
