package:
  name: ophyd
  version: v0.1.2


source:
  git_url: https://github.com/NSLS-II/ophyd
  git_rev: v0.1.2

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pyepics
    - pcaspy
    - metadatastore
    - six
    - ipython
    - boltons
    - pyolog >=v4.0.0.post5+g1a24409
    - channelarchiver >=0.0.5.post6
    - pyepics >=v3.2.4.post19+g763d30

test:
  # Python imports
  imports:
    - ophyd
    - ophyd.controls
    - ophyd.controls.areadetector
    - ophyd.controls.cas
    - ophyd.session
    - ophyd.utils

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/NSLS-II/ophyd
  license: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
