package:
  name: bluesky
  version: v0.2.3

source:
  git_url: https://github.com/NSLS-II/bluesky
  git_rev: v0.2.3

build:
  number: 0

requirements:
  build:
    - python ==3.4.3

  run:
    - python >=3.4.3
    - jsonschema
    - super_state_machine
    - numpy
    - metadatastore
    - filestore
    - matplotlib
    - prettytable
    - cycler
    - traitlets
    - history
    - lmfit

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - 'bluesky'
    - 'bluesky.examples'

about:
  home: https://github.com/NSLS-II/bluesky
  license: BSD
