package:
  name: nslsii_dev_configuration
  version: '1'

build:
  number: 2

requirements:
  run:
    - conda_etc

about:
  summary: 'Development environment configurations to point metadatastore and filestore at localhost'
