
package:
    name: pyolog
    version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
    git_url: https://github.com/NSLS-II-CSX/pyOlog.git
    git_tag: master

build:
    string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - setuptools
        - requests
        - keyring
        - six
        - ipython

test:
    imports:
        - pyOlog
        # this has a user input on import (?!?) so don't test
        #- pyOlog.cli.ipy

about:
    home: http://olog.github.io/
    license: MIT
    summary: Python client for the OLog
