package:
  name: filestore
  version: 'v0.0.4'

source:
  git_url: https://github.com/NSLS-II/filestore.git
  git_rev: 'v0.0.4'

build:
  number: 0


requirements:
  build:
    - python
    - six

  run:
    - python
    - mongoengine
    - h5py
    - numpy
    - six
    - pyyaml
    - jsonschema
    - pims
    - tifffile

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - filestore
    - filestore.api
    - filestore.commands
    - filestore.conf
    - filestore.file_writers
    - filestore.handlers
    - filestore.odm_templates
    - filestore.retrieve
    - filestore.utils
