package:
  name: libevent
  version: 2.0.22

build:
  number: 0

source:
  fn: libevent-2.0.22-stable.tar.gz
  url: https://sourceforge.net/projects/levent/files/libevent/libevent-2.0/libevent-2.0.22-stable.tar.gz

#requirements:
#  build:
#    gcc
#
#  run:
#
about:
  license: BSD
  home: http://libevent.org
  summary: an event notification library
