package:
  name: filestore
  version: 'v0.0.2'

source:
  git_url: https://github.com/NSLS-II/filestore.git
  git_rev: 'v0.0.2'

build:
  number: 2


requirements:
  build:
    - python
    - six

  run:
    - python
    - mongoengine
    - h5py
    - numpy
    - six

test:
  imports:
    - filestore
    - filestore.api
    - filestore.commands
    - filestore.conf
    - filestore.file_writers
    - filestore.handlers
    - filestore.odm_templates
    - filestore.retrieve
    - filestore.utils
