package:
  name: fabio
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/kif/fabio.git
  git_tag: master

requirements:
  build:
    - python
    - numpy
    - cython
    - pillow
  run:
    - python
    - numpy
    - pillow

test:
  imports:
    - fabio

about:
  license: GPL
  home: https://github.com/kif/fabio
  summary: Fable I/O library for diffraction images
