
package:
    name: characteristic
    version: "14.3.0"

source:
    fn: characteristic-14.3.0.tar.gz
    url: https://pypi.python.org/packages/source/c/characteristic/characteristic-14.3.0.tar.gz
    md5: b249368dd021fde1c06b4802867c0913

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - characteristic

about:
    home: http://characteristic.rtfd.org/
    license: MIT
    summary: Python attributes without boilerplate 
