package:
  name: csx2_analysis
  version: '0.1'


build:
  number: 0


requirements:
  run:
    - csx2_configuration
    - matplotlib
    - dataportal
    - openpyxl
    - ipython-notebook
    - vistrails
    - scikit-xray
