package:
  name: dataportal
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/NSLS-II/dataportal.git
  git_rev: master
  patches:
    - setup_py.patch
build:
  string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}
  number: 0

  entry_points:
    - replay = dataportal.replay.replay:main

requirements:
  build:
    - python
    - enaml [py2k]
    - numpy
    - six

  run:
    - python
    - pandas
    - matplotlib
    - pyyaml
    - enaml [py2k]
    - bubblegum [py2k]
    - scikit-xray [py2k]
    - pims [py2k]
    - metadatastore
    - filestore
    - channelarchiver
    - six

test:
  imports:
    - 'dataportal'
    - 'dataportal.api'
    - 'dataportal.testing'
    - 'dataportal.examples'
    - 'dataportal.examples.sample_data'
    - 'dataportal.broker'
    - 'dataportal.muxer'
    - 'dataportal.sources'
    - 'dataportal.sources.dummy_sources'
    - 'dataportal.utils'
    - 'dataportal.replay'
    - 'dataportal.replay.muxer'  [py2k]
    - 'dataportal.replay.scalar' [py2k]
    - 'dataportal.replay.search' [py2k]