package:
    name: ophyd
    version: {{ environ.get('GIT_DESCRIBE_TAG','')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER','') }}

source:
    git_url: https://github.com/NSLS-II/ophyd.git
    git_rev: master

  # use a local url and leave rev blank to have conda build current head, currently
  # requires master branch of conda-build to work
  # git_rev: ?

build:
    number: 0
    string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}

requirements:
    build:
      - python
      - setuptools
  
    run:
      - python
      - readline
      - pyepics
      - databroker
      - metadatastore
      - pyolog
      - pcaspy

test:
  # Python imports
  imports:
    - ophyd
    - ophyd.controls
    - ophyd.controls.areadetector
    - ophyd.runengine
    - ophyd.session
    - ophyd.userapi
    - ophyd.utils
    - ophyd.writers

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/NSLS-II/ophyd
  license: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
