package:
  name: metadatastore
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/NSLS-II/metadatastore.git
  git_rev: master
  # use a local url and leave rev blank to have conda build current head, currently
  # requires master branch of conda-build to work
  # git_rev: ?

build:
  string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}
  number: 0

requirements:
  build:
    - python
    - six

  run:
    - python
    - mongoengine
    - six
    - pyyaml
    - pandas

test:
  requires:
    - nslsii_dev_configuration

  # Python imports
  imports:
    - metadatastore
    - metadatastore.commands
    - metadatastore.api
    - metadatastore.conf
    - metadatastore.odm_templates
    - metadatastore.document
    - metadatastore.utils
