package:
  name: pcaspy
  version: 0.5.1

source:
  fn: pcaspy-0.5.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pcaspy/pcaspy-0.5.1.tar.gz
  md5: ba8c56ef136540cbaa463d35385b4c42
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyasn1-modules = pyasn1-modules:main
    #
    # Would create an entry point called pyasn1-modules that calls pyasn1-modules.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 2

requirements:
  build:
    - python
    - setuptools
    - epics-base
    - swig

  run:
    - python
    - epics-base

test:
  # Python imports
  imports:
    - pcaspy

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    # - reindent --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://code.google.com/p/pcaspy/
  license: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
