package:
    name: carchivetools
    version: 2.2.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
    git_url: https://github.com/tacaswell/carchivetools
    git_rev: fix_py3k

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - numpy
        - protobuf
        - service_identity
    run:
        - python
        - numpy
        - twisted
        - protobuf
        - service_identity

test:
    imports:
        - carchive

about:
    home: https://github.com/epicsdeb/carchivetools
    summary: Channel Archiver shell tools and library
