
package:
    name: epics-base
    version: "3.14.12"

source:
    fn: baseR3.14.12.4.tar.gz
    url: http://www.aps.anl.gov/epics/download/base/baseR3.14.12.4.tar.gz

build:
  number: 0

requirements:
  build:
    - readline

  run:
    - readline

about:
    home: http://www.aps.anl.gov/epics
    license: Epics Open License
    summary: EPICS Base Library
