
package:
    name: epics-base
    version: "3.15.1"

source:
    fn: base-3.15.1.tar.gz
    url: http://www.aps.anl.gov/epics/download/base/base-3.15.1.tar.gz

build:
    number: 0

about:
    home: http://www.aps.anl.gov/epics
    license: Epics Open License
    summary: EPICS Base Library
