package:
  name: breathe
  version: 4.1.0

build:
  number: 0

source:
  git_url: https://github.com/michaeljones/breathe.git
  git_rev: v4.1.0

requirements:
  build:
    - python
    - setuptools
    - six
    - docutils
    - sphinx

  run:
    - python
    - sphinx
    - docutils
    - six

about:
  license: BSD
  home: http://breathe.readthedocs.org/en/latest/
  summary: Breathe provides a bridge between the Sphinx and Doxygen documentation systems.
