package:
  name: dataportal
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/NSLS-II/dataportal.git
  git_rev: master

build:
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}
  number: 0

  entry_points:
    - replay = dataportal.replay.replay:main

requirements:
  build:
    - python
    - six

  run:
    - python
    - pandas
    - matplotlib
    - pyyaml
    - pims
    - metadatastore
    - filestore
    - channelarchiver
    - six

test:
  imports:
    - dataportal
    - dataportal.api
    - dataportal.testing
    - dataportal.examples
    - dataportal.examples.sample_data
    - dataportal.broker
    - dataportal.muxer
    - dataportal.sources
    - dataportal.sources.dummy_sources
    - dataportal.utils

about:
  home: https://github.com/NSLS-II/dataportal
  license: BSD
