package:
  name: dataportal
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/NSLS-II/dataportal
  git_rev: master

build:
  number: 0

  # Note that this will override the default build string with the Python
  #   # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}

requirements:
  build:
    - python

  run:
    - python
    # still needed because StepScan
    - pandas
    - six
    - databroker
    - datamuxer

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - dataportal
    - dataportal.api
    - dataportal.testing
    - dataportal.examples
    - dataportal.examples.sample_data
    - dataportal.broker
    - dataportal.muxer
    - dataportal.utils

about:
  home: https://github.com/NSLS-II/dataportal
  license: BSD
