
package:
    name: epics-base
    version: "3.14.12.4"

source:
    fn: baseR3.14.12.4.tar.gz
    url: http://www.aps.anl.gov/epics/download/base/baseR3.14.12.4.tar.gz
    patches:
        - config_site.diff
        - config_common.diff

build:
  number: 0

requirements:
  build:
#    - perl
    - readline

  run:
    - readline

about:
    home: http://www.aps.anl.gov/epics
    license: Epics Open License
    summary: EPICS Base Library
