package:
  name: libffi
  version: 3.2.1

source:
  fn: libffi-3.2.1.tar.gz
  url: ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz
  # url: http://pkgs.fedoraproject.org/repo/pkgs/libffi/libffi-3.0.13.tar.gz/45f3b6dbc9ee7c7dfbbbc5feba571529/libffi-3.0.13.tar.gz
  md5: 83b89587607e3eb65c70d361f13bab43

build:
  number: 8

about:
  home: https://sourceware.org/libffi/
  license: BSD
  summary: Compilers for high level languages generate code that follows certain conventions.
