package:
  name: doct
  version: {{ environ['GIT_DESCRIBE_TAG'][1:] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/NSLS-II/doct.git
  git_rev: master

build:
  number: 0

  # Note that this will override the default build string with the Python
  # and NumPy versions


requirements:
  build:
    - python

  run:
    - python
    - six

test:
  imports:
    - doct
