package:
  name: collection
  version: '2016_01'
# https://github.com/ericdill/conda-prescriptions/blob/add-dp-v0.2.2/beamline-environments/proposed-deployment-strategy.rst


build:
  number: 0

requirements:
  run:
   - bluesky
   - ophyd
   - xray_vision
   - pyolog