package:
  name: pyspec
  version: 0.2.0

source:
  git_url: https://github.com/stuwilkins/pyspec.git

build:
  number: 0

requirements:
  build:
    - setuptools
    - python
    - numpy
    - scipy
    - matplotlib

  run:
    - python
    - numpy
    - scipy
    - matplotlib

test:
  # Python imports
  imports:
    - pyspec
    - pyspec.fit
    - pyspec.fitfuncs

about:
  home: http://github.com/stuwilkins/pyspec
  license: GPL

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
