
package:
    name: service_identity
    version: "14.0.0"

source:
    fn: service_identity-14.0.0.tar.gz
    url: https://pypi.python.org/packages/source/s/service_identity/service_identity-14.0.0.tar.gz
    md5: cea0b0156d73b025ecef660fb51f0d9a

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - pyopenssl
        - pyasn1
        - pyasn1-modules
        - characteristic
    run:
        - python
        - pyopenssl
        - pyasn1
        - pyasn1-modules
        - characteristic

test:
    imports:
        - service_identity

about:
    home: https://pypi.python.org/pypi/service_identity
    license: MIT
    summary: Service identity verification for pyOpenSSL
