package:
  name: reindent
  version: !!str 0.1.1

source:
  fn: Reindent-0.1.1.tar.gz
  url: https://pypi.python.org/packages/source/R/Reindent/Reindent-0.1.1.tar.gz
  md5: 878352c36c421a0b944607efba3b01ad
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyasn1-modules = pyasn1-modules:main
    #
    # Would create an entry point called pyasn1-modules that calls pyasn1-modules.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  #imports:
  #  - 

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - reindent --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://pypi.python.org/pypi/Reindent
  license: Public Domain
  summary: 'reindent script by Tim Peters'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
