package:
    name: hdf5-lz4
    version: 0.2

source:
    git_url: https://github.com/dectris/HDF5Plugin.git
    git_tag: 8fa813aa369c15127c551cfdeebe4cbc090b4687  # no tags in repo

build:
    number: 2

requirements:
    build:
        - hdf5
    run:
        - hdf5
        - conda-env >2.1.4  # when $CONDA_ENV_PATH was added

about:
    home: https://github.com/dectris/HDF5Plugin
    license: BSD-2
