package:
  name: twisted
  version: "15.4.0"

source:
  fn: Twisted-15.4.0.tar.bz2
  url: https://pypi.python.org/packages/source/T/Twisted/Twisted-15.4.0.tar.bz2
  md5: 5337ffb6aeeff3790981a2cd56db9655
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - twisted = twisted:main
    #
    # Would create an entry point called twisted that calls twisted.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - zope.interface >=4.0.2

  run:
    - python
    - zope.interface >=4.0.2

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://twistedmatrix.com/
  license: MIT
  summary: 'An asynchronous networking framework written in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
