package:
  name: python
  version: 3.4.2

source:
  fn: Python-3.4.2.tgz
  url: https://www.python.org/ftp/python/3.4.2/Python-3.4.2.tgz
  md5: 5566bc7e1fdf6bed45f9a750d5f80fc2
  patches:
    #- setup-with-debug-output.patch

build:
  number: 11

requirements:
  build:
    - bzip2 1.0.6
    - openssl 1.0.1*
    - readline 6.2*
    - sqlite 3.8.*
    - system 5.8
    - tk 8.5.*
    - xz 5.0.*
    - zlib 1.2.*
  run:
    # The bzip2-1.0.6 package contains a static library only; therefore it is
    # not required at runtime.
    - openssl 1.0.1*
    - readline 6.2*
    - sqlite 3.8.*
    - system 5.8
    - tk 8.5.*
    - xz 5.0.*
    - zlib 1.2.*

about:
  home: https://www.python.org/
  license: PSF
