package:
  name: python
  version: "2.7.9"

source:
  fn: Python-2.7.9.tgz
  url: https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz
  md5: 5eebcaa0030dc4061156d3429657fb83
  patches:
    - setup-fixdirs.patch
    #- setup-fixdirs-with-debug-output.patch

build:
  number: 11

requirements:
  build:
    - bzip2 1.0.6
    - openssl 1.0.1*
    - readline 6.2.*
    - sqlite 3.8.*
    - system 5.8
    - tk 8.5.*
    - zlib 1.2.*
  run:
    # The bzip2-1.0.6 package contains a static library only; therefore it is
    # not required at runtime.
    - openssl 1.0.1*
    - readline 6.2.*
    - sqlite 3.8.*
    - system 5.8
    - tk 8.5.*
    - zlib 1.2.*

about:
  home: https://www.python.org/
  license: PSF
