package:
  name: metadataclient
  version: {{ environ.get('GIT_DESCRIBE_TAG','v0')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
  git_url: https://github.com/NSLS-II/metadataclient.git
  git_rev: master
  patches:
    - config.patch

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - six
    - pyyaml
    - pytz
    - requests
    - ujson
    - doct

test:
  requires:
    - nslsii_dev_configuration

  # Python imports
  imports:
    - metadataclient
    - metadataclient.commands
    - metadataclient.api
    - metadataclient.conf
    - metadataclient.utils

about:
  home: https://github.com/NSLS-II/metadataclient
  license: BSD
