
package:
    name: pyepics
    version: "3.2.4"

source:
    git_url: https://github.com/NSLS-II-CSX/pyepics.git

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
        - epics-base
    run:
        - python
        - epics-base

test:
    imports:
        - epics

about:
    home: http://pyepics.github.io/pyepics/
    license: Epics Open License
    summary: Python interface to Epics Channel Access
