package:
  name: args
  version: 0.1.0

source:
  git_url: https://github.com/kennethreitz/args
  git_rev: v0.1.0

requirements:
  build:
    - python
    - pip

  run:
    - python

about:
  home: https://github.com/kennethreitz/args
  license: BSD License
  summary: Command Arguments for Humans.
