package:
  name: mako
  version: !!str 1.0.1

source:
  fn: Mako-1.0.1.tar.gz
  url: https://pypi.python.org/packages/source/M/Mako/Mako-1.0.1.tar.gz
  md5: 9f0aafd177b039ef67b90ea350497a54

build:
  number: 0

requirements:
  build:
    - python
    - pip
    - markupsafe

  run:
    - python
    - markupsafe

test:
  imports:
    - mako

about:
  home: http://www.makotemplates.org/
  license: MIT
  summary: A super-fast templating language that borrows the  best ideas from the existing templating languages.
