package:
  name: slicerator
  version: "0.9.4"

source:
  fn: slicerator-0.9.4.tar.gz
  url: https://pypi.python.org/packages/source/s/slicerator/slicerator-0.9.4.tar.gz
  md5: 326841c72a596816198f088d2c430863
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - slicerator = slicerator:main
    #
    # Would create an entry point called slicerator that calls slicerator.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  # Python imports
  imports:
    - slicerator

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/soft-matter/slicerator
  license: BSD
  summary: 'A lazy-loading, fancy-sliceable iterable.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
