package:
  name: analysis
  version: '0.1'

build:
  number: 0

requirements:
  run:
    - python ==3.4
    - dataportal >=0.2.2
    - channelarchiver >=v0.0.5.post6
    - lmfit >=0.9.0rc1.post0
    - matplotlib >=1.5.0rc1
    - album >=v0.0.1
    - scikit-xray >=v0.0.5
    - xray-vision >=v0.0.3
    - pims >=v0.3.0rc1