package:
  name: analysis
  version: '2015-03'

build:
  number: 1

requirements:
  run:
    - bluesky >=v0.2.3
    - python ==3.4.3
    - jupyter
    - ipywidgets
    - pymongo <3.0
    - dataportal >=v0.2.2
    - channelarchiver
    - lmfit >=0.9.0
    - matplotlib >= 1.5.0rc1
    - openpyxl
    - scikit-xray >=v0.5.0
    - xray-vision >=v0.3.0
    - album >=v0.0.1
