package:
  name: analysis
  version: '0.1'

build:
  number: 5

requirements:
  run:
    - python ==3.4.3
    - ipython-notebook
    - ipywidgets
    - dataportal >=0.2.2
    - channelarchiver
    - lmfit
    - matplotlib
    - album
    - scikit-xray
    - xray-vision
